### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Z3dKay** [VectorCamp/vectorscan#137]
Hi, I know this isn't the place to write about this but I'm struggling to understand how to install vectorscan. Does it require hyperscan to be installed or is it standalone?
Also I don't want to cross-compile as I'm trying to install it directly on my Raspberry Pi 4 with DietPi OS (Debian-based) x64 ARMv8 Bullseye. How should I go about configuring _cmake/setenv-arm64-cross.sh_ as mentioned in README?

Thank you

**Comment by markos** [comment]
Hi @Z3dKay. Vectorscan is meant to be a drop-in replacement for hyperscan. It is already packaged for Debian, but it's not yet migrated to testing: https://tracker.debian.org/pkg/vectorscan

You could just grab the debian packages and install on your arm64 system with no problems. I hope I helped.

**Comment by Z3dKay** [comment]
![image](https://user-images.githubusercontent.com/94125880/201189835-a4e8e114-3c4a-4bf8-ac2d-70ac0840a74b.png)

So only the last 2 instructions apply to me?

**Comment by markos** [comment]
it's in the plans to send bug reports to Debian snort packages to allow enabling vectorscan on Arm instead of hyperscan.
If you want to build from source on the Pi, there is no cross-compiling involved -and the instructions are old incorrect unfortulately, apologies for that. So to build ON the Pi you only have to do the following:

(inside vectorscan directory)```

mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -jT
make install
```

That should install the same libraries as hyperscan and they will be detected by snort.

**Comment by Z3dKay** [comment]
Thank you so much for the help, much appreciated. That is all for now, onto installing snort 3. Will see if it works.
