### ISSUE TITLE
Version comparison between that of Intel Hyperscan

### ISSUE THREAD

**Issue by TrevorTaoARM** [VectorCamp/vectorscan#24]
I see that the latest version of vectorscan is 5.4.2+vectorscan(anything newer?), I am curious here what's the comparable version of Hyperscan of Intel release(https://github.com/intel/hyperscan).

It seems there are some code differences between v5.4.2+vectorscan and the release of v5.4.0 of Intel Hyperscan.
So what's the base release of v5.4.2+vectorscan for which we revised from?

**Comment by markos** [comment]
@TrevorTaoARM we forked originally from 5.3.0 and then rebased on Intel's 5.4.0, however before we added the +vectorscan suffix, we did some extra changes on top of that, hence the .2. We are working on a major SIMD refactoring and we will probably use a different versioning scheme because of that, but it is not decided yet. Suffice to say, feature-wise and ABI/API-wise, we're totally compatible with Intel's 5.4.0 version.
