### ISSUE TITLE
Fix all errors/warnings found by CPPcheck

### ISSUE THREAD

**Issue by gtsoul-tech** [VectorCamp/vectorscan#252]
1 accessMoved  PR:#254 
1 unsignedLessThanZero PR:#254 
1 comparisonOfBoolWithBoolError PR:#254 
1 funcArgOrderDifferent PR:#254 
1 legacyUninitvar PR:#254 
1 useInitializationList PR:#254 
1 redundantContinue PR:#254
1 virtualCallInConstructor
2 containerOutOfBounds PR:#255
2 comparisonOfTwoFuncsReturningBoolError PR:#255
2 duplicateAssignExpression PR:#255
2 knownEmptyContainer PR:#255
2 truncLongCastAssignment PR:#255
2 noConstructor PR:#255
2 passedByValue PR:#255
2 duplicateCondition PR:#255
2 unknownMacro PR:#255
2 unusedVariable PR:#255
2 identicalConditionAfterEarlyExit PR:#255
 3 invalidPrintfArgType_sint PR:#256
3 uninitvar #256
3 shiftTooManyBitsSigned PR:#256
5 nullPointerRedundantCheck PR:#257
6 invalidPrintfArgType_uint PR:#257
6 uninitMemberVar PR:#257
6 arithOperationsOnVoidPointer PR:#257
7 redundantInitialization PR:#256
2(10) derefInvalidIteratorRedundantCheck PR:#256
11 badBitmaskCheck PR:#256
12 syntaxError PR:#258
20 constParameterPointer PR:#258
32 missingOverride  PR:#259
35 variableScope PR:#259
41 unreadVariable PR:#261
47 constParameterReference PR:#262
48 constVariableReference PR:#262
58 constVariable PR:#262
71 knownConditionTrueFalse PR:#263
66 shadowFunction PR:#265
TODO:      67 missingInclude
101 constVariablePointer #264
TODO:     177 unusedFunction
207 noExplicitConstructor PR: #274
271 useStlAlgorithm  PR: #277 #283
784 cstyleCast PR: #281 #284 #285 #286 #287 #289 #291

https://buildbot-ci.vectorcamp.gr/#/builders/269/builds/2/steps/5/logs/stdio

false-positives:

- uselessAssignmentArg   PR:#267
- redundantAssignment   PR:#270
- redundantPointerOp      src/util/partitioned_set.h PR: #291 
- returnDanglingLifetime  src/parser/Parser.rl:167:12 PR: #291 
- pointerLessThanZero      src/parser/control_verbs.rl:111:16 PR: #291 
- pointerPositive                src/parser/control_verbs.rl:111:16 PR: #291 
- constParameterCallback simplegrep.c:70:74 PR: #278 
- duplInheritedMember    src/nfagraph/ng_holder.h:117:25 PR: #291 
- unsignedPositive            src/util/partitioned_set.h:231:29 PR: #291 
- checkLevelNormal          specify --check-level=exhaustive ADDED

- 4 duplicateExpression PR: #279 

-  4 constStatement  PR: #268 
- 8 derefInvalidIteratorRedundantCheck NOT APPLICABLE ANYMORE

- 11 assertWithSideEffect PR: #291 

false positives ignored in PR 255:

- containerOutOfBounds      src/rose/rose_build_add_mask.cpp:192 PR: #291 
- containerOutOfBounds      benchmarks/benchmarks.cpp:243 PR: #291 
- duplicateAssignExpression  PR: #269
- identicalConditionAfterEarlyExit  PR:#271
- knownEmptyContainer      src/nfa/goughcompile.cpp:924 PR: #291 
- noConstructor    unit/internal/repeat.cpp:67 PR: #291 
- noConstructor    unit/internal/repeat.cpp:730 PR: #291 
- truncLongCastAssignment   PR:#272
- unknownMacro src/parser/ucp_table.h:818. PR: #279 
- unknownMacro     unit/gtest/gtest-all.cc:1686 PR: #291 

false positives from PR 257:
- nullPointerRedundantCheck src/nfa/nfa_api_queue.h:254 PR: #279 
                 
- arithOperationsOnVoidPointer        unit/internal/multi_bit.cpp:58: PR: #291 
- arithOperationsOnVoidPointer       unit/internal/multi_bit_compress.cpp:97 PR: #291 
                 
- uninitMemberVar           PR: #291 

false positives from PR 258:
- syntaxError       PR: #291 

- constParameterPointer     src/nfa/limex_runtime_impl.h:930 PR: #278 
- constParameterPointer     src/nfa/goughcompile.cpp:662 PR: #278 

false positives ignored in PR 261:
Most are used in debug macros
unreadVariable 	src/stream_compress_impl.h:145:21.  PR: #279 
unreadVariable	src/hwlm/hwlm.c:173:33    PR: #278 
unreadVariable	src/rose/match.c:271:38 PR: #279 		
unreadVariable	src/fdr/fdr_confirm_compile.cpp:297:51 PR: #279 
unreadVariable	src/nfa/dfa_min.cpp:307:39	PR: #279 
unreadVariable	src/nfa/mcsheng_compile.cpp:1021:25 PR: #279 			
unreadVariable	src/nfa/shengcompile.cpp:789:21	 PR: #279 
unreadVariable	src/nfagraph/ng_repeat.cpp:858:44 PR: #279 
unreadVariable	src/nfagraph/ng_som.cpp:3136:16 PR: #279 	
unreadVariable	src/parser/control_verbs.cpp:89:18	PR: #291 
unreadVariable	src/rose/rose_build_add.cpp:1042:33	PR: #279 
unreadVariable	src/rose/rose_build_long_lit.cpp:101:18   PR: #279 
unreadVariable	src/rose/rose_build_misc.cpp:864:19	PR: #279 
unreadVariable	unit/internal/state_compress.cpp:183:25 PR: #279 
unreadVariable	util/cross_compile.cpp:58:17. PR: #279 
unreadVariable	unit/internal/multi_bit_compress.cpp PR: #279 

false positives from PR262:
constParameterReference  src/nfa/goughcompile.cpp:444:72: PR: #278 
constParameterReference  src/nfa/mcsheng_compile.cpp:537:  PR: #278 
constVariableReference  src/nfagraph/ng_limex_accel.cpp:466:   PR: #291 
constParameterReference  src/rose/rose_build_anchored.cpp:870:  PR: #278 

false positives from PR263:
knownConditionTrueFalse PR: #291 (multiple)
src/hs_valid_platform.c:51:18:  PR: #279 
src/nfagraph/ng_puff.cpp  PR:#273
src/nfagraph/ng_som.cpp  PR:#273
src/nfagraph/ng_violet.cpp PR:#273
src/rose/rose_build_convert.cpp PR:#273

false positives from PR #264:
src/parser/prefilter.cpp:350:16  PR: #291 

ignored in PR  #274
src/util/flat_containers.h:65:5  PR: #291 
src/util/insertion_ordered.h:67:5   PR: #291 
src/parser/position_info.h:40:5  PR: #291 
src/util/supervector/supervector.hpp:208:3 #276 
src/util/supervector/supervector.hpp:211:3 #276 

ignored in PR 277:
src/fdr/teddy_engine_description.cpp:74: useStlAlgorithm  PR: #291

**Comment by isildur-g** [comment]
covered in PR 255:

2 [comparisonOfTwoFuncsReturningBoolError]
2 [containerOutOfBounds]
2 [duplicateAssignExpression]
2 [duplicateCondition]
2 [identicalConditionAfterEarlyExit]
2 [knownEmptyContainer]
2 [noConstructor]
2 [passedByValue]
2 [truncLongCastAssignment]
2 [unknownMacro]
2 [unusedVariable]

false positives ignored in PR 255:

src/rose/rose_build_add_mask.cpp:192:18
: error: Out of bounds access in expression 'curr.back()' because 'curr' is empty. [containerOutOfBounds]
this one is a false positive

/benchmarks/benchmarks.cpp:243:20: error
: Out of bounds access in 'str[char_len+1]', if 'str' size is 6 and 'char_len+1' is 6 [containerOutOfBounds]
could actually be a different bug here, the way that code reads it looks like the writer
intended to use j there and not char_len. left a comment.

src/scratch.c:85:9: style: Same expression used in consecutive assignments of 'som_store_size' and 'som_attempted_store_size'. [dupl
icateAssignExpression]
false positive

/var/lib/buildbot/workers/runner-d13-aarch64-01/release-linux-aarch64-gcc-14-cppcheck/source/src/parser/ComponentBoundary.cpp:171:12
: warning: Identical condition and return expression 'at_start', return value is always false [identicalConditionAfterEarlyExit]

false positive, the logic there makes sense as it is.

/var/lib/buildbot/workers/runner-d13-aarch64-01/release-linux-aarch64-gcc-14-cppcheck/source/src/parser/ComponentBoundary.cpp:183
: warning: Identical condition and return expression 'at_end', return value is always false [identicalConditionAfterEarlyExit]

false positive, the logic there makes sense as it is.

/var/lib/buildbot/workers/runner-d13-aarch64-01/release-linux-aarch64-gcc-14-cppcheck/source/src/nfa/goughcompile.cpp:924:24: style:
Iterating over container 'eji' that is always empty. [knownEmptyContainer]

false positive, the very line before that is probably going to populate that value.

/var/lib/buildbot/workers/runner-d13-aarch64-01/release-linux-aarch64-gcc-14-cppcheck/source/unit/internal/repeat.cpp:67:1: style: T
he class 'RepeatTest' does not declare a constructor although it has private member variables which likely require initialization. [
noConstructor]
false positive. it has a setup function which looks like it does everything a constructor would do.

/var/lib/buildbot/workers/runner-d13-aarch64-01/release-linux-aarch64-gcc-14-cppcheck/source/unit/internal/repeat.cpp:730:1: style:
The class 'SparseOptimalTest' does not declare a constructor although it has private member variables which likely require initializ
ation. [noConstructor]
same thing, it has a SetUp finction which does the work of a constructor.

/var/lib/buildbot/workers/runner-d13-aarch64-01/release-linux-aarch64-gcc-14-cppcheck/source/tools/hsbench/huge.cpp:186:20: style: i
nt result is assigned to long variable. If the variable is long to avoid loss of information, then you have loss of information. [tr
uncLongCastAssignment]
false positive. the types are for compatibility with the functions called and the required return value,
the actual values which would ever be encountered will never risk an overflow. besides long is the same as int in almost any machine
this would ever be compiled on.

/var/lib/buildbot/workers/runner-d13-aarch64-01/release-linux-aarch64-gcc-14-cppcheck/source/src/parser/ucp_table.h:818:1: error: Th
ere is an unknown macro here somewhere. Configuration is required. If UCP_FN is a macro then please configure it. [unknownMacro]
UCP_FN(C)

false positive. the .h file has a warning that it is autogenerated. the macro is defined in the cpp and the .h
is included shortly below. the macro is known at compile time.

/var/lib/buildbot/workers/runner-d13-aarch64-01/release-linux-aarch64-gcc-14-cppcheck/source/unit/gtest/gtest-all.cc:1686:17: error:
There is an unknown macro here somewhere. Configuration is required. If GTEST_NAME_ is a macro then please configure it. [unknownMa
cro]
"True iff " GTEST_NAME_
false positive. it's defined in gtest.h which is included in that file.
