### ISSUE TITLE
the actual type of char is different on different platforms

### ISSUE THREAD

**Issue by necuil** [VectorCamp/vectorscan#98]
On android devices, char is unsigned, unlike PC. In the function unique_ptr<Component> parse(const char *ptr, ParseMode &globalMode), it assigns the content of each byte to a variable of type short by accessing a char pointer. On android devices, this step can have unexpected results. So it should be int8_t not char.
<img width="1875" alt="16492300306567" src="https://user-images.githubusercontent.com/43336757/162178220-e76918a9-17d5-4223-a353-9a01db8da978.png">
And after I replace those "char" with "int8_t" or "uint8_t", vectorscan works fine on my android device.

**Comment by markos** [comment]
is this 32-bit arm or 64-bit arm? This is not a bad suggestion, I would not mind checking such a PR if you would be willing to submit one, but at the moment I cannot commit to working on this, as Android is not within the supported platforms yet. In fact, I could not think of a usecase for Android until now :)

**Comment by necuil** [comment]
both 32-bit arm and 64-bit arm

**Comment by markos** [comment]
Hi @necuil, we are cleaning up some issues. Regarding Android and 32-bit Arm we have decided we will not support 32-bit arm at this moment and definitely not Android unless the changes are required are minimal and someone else submits a PR for this or funds this effort. Since the request was made already 6 months ago, it's already an old issue. I will be closing this issue as wontfix.

**Comment by markos** [comment]
Closing this as arm is now a supported platform and works as expected.
